### ISSUE TITLE
freeze_support() error while running generate_data.py

### ISSUE THREAD

**Issue by santhosh1299** [hassan-mahmood/TIES_DataGeneration#19]
(venv) C:\Users\20316562\PycharmProjects\pythonProject\Table Gen>python generate_data.py  --filesize 1 --threads 1  --outpath "tfrecords/"  --imagespath "Table Gen/data/unlv_images"  --oc
rpath "Table Gen/data/unlv_xml_ocr"   --tablepath "Table Gen/data/unlv_xml_gt" --visualizeimgs 0  --visualizebboxes 0
2021-06-16 12:19:59.343536: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
2021-06-16 12:20:22.431223: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\20316562\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\20316562\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\20316562\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\20316562\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\20316562\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\20316562\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\20316562\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\20316562\PycharmProjects\pythonProject\Table Gen\generate_data.py", line 31, in <module>
    t.write_to_tf(args.threads)
  File "C:\Users\20316562\PycharmProjects\pythonProject\Table Gen\TFGeneration\GenerateTFRecord.py", line 332, in write_to_tf
    proc.start()
  File "C:\Users\20316562\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\20316562\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\20316562\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\20316562\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\20316562\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\20316562\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
5.963414430618286

**Comment by CC-todo** [comment]
if __name__ == '__main__':
    filesize = max(int(args.filesize), 4)
    visualizeimgs = False
    if (args.visualizeimgs == 1):
        visualizeimgs = True

    visualizebboxes = False
    if (args.visualizebboxes == 1):
        visualizebboxes = True

    distributionfile = 'unlv_distribution'

    t = GenerateTFRecord(args.outpath, filesize, args.imagespath,
                         args.ocrpath, args.tablepath, visualizeimgs, visualizebboxes, distributionfile)
    t.write_to_tf(args.threads)
